### ISSUE TITLE
I want to convert a .KMZ file from Google maps to .xlsx. I get the message "Column 'WKT' is missing" and don't know where to go from there. Anyone to help? 

### ISSUE THREAD

**Issue by JanneSandberg** [aspose-free-consulting/projects#280]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to Aspose APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.aspose.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by evgeniy-timofeev-aspose** [comment]
We had some problem with the xls format. We have corrected it. Please check if it works.

**Comment by JanneSandberg** [comment]
Hi,

 

Thank’s for answering. Still getting the same problem though.



 

     Med Vänliga Hälsningar

     Best Regards

 

     Jan Sandberg



     Ramsta-Lund 36             Tel: +46 (0)70 219 82 30

     755 91 Uppsala              Mail:  ***@***.***> ***@***.***

 

Från: evgeniy-timofeev-aspose ***@***.***> 
Skickat: den 13 februari 2023 07:48
Till: aspose-free-consulting/projects ***@***.***>
Kopia: JanneSandberg ***@***.***>; Author ***@***.***>
Ämne: Re: [aspose-free-consulting/projects] I want to convert a .KMZ file from Google maps to .xlsx. I get the message "Column 'WKT' is missing" and don't know where to go from there. Anyone to help? (Issue #280)

 

We had some problem with the xls format. We have corrected it. Please check if it works.

**Comment by JanneSandberg** [comment]
Hi again,

 

Any progress with this?

 

BR Janne

 

 

 

Hi,

 

Thank’s for answering. Still getting the same problem though.



 

     Med Vänliga Hälsningar

     Best Regards

 

     Jan Sandberg



     Ramsta-Lund 36             Tel: +46 (0)70 219 82 30

     755 91 Uppsala              Mail:  ***@***.***> ***@***.***

 

Från: evgeniy-timofeev-aspose ***@***.***> 
Skickat: den 13 februari 2023 07:48
Till: aspose-free-consulting/projects ***@***.***>
Kopia: JanneSandberg ***@***.***>; Author ***@***.***>
Ämne: Re: [aspose-free-consulting/projects] I want to convert a .KMZ file from Google maps to .xlsx. I get the message "Column 'WKT' is missing" and don't know where to go from there. Anyone to help? (Issue #280)

 

We had some problem with the xls format. We have corrected it. Please check if it works.

**Comment by evgeniy-timofeev-aspose** [comment]
I have created a ticket GISNET-1412 and update you here as soon as additional information is available.

Please feel free to contact us if you have any other issues.
